name: Auto Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change if your branch name is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@master
        with:
          host: techifys.com
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            cd public_html
            git pull origin main
